#
# Copyright (C) 2026 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#
DEVICE_PATH := device/denver/TAQ90

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic
# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := recovery
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 160

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 0
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := false
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 15681536
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15681536
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := rk3126c

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TW_THEME := landscape_mdpi
TARGET_SCREEN_WIDTH := 1024
TARGET_SCREEN_HEIGHT := 600
TW_EXTRA_LANGUAGES := false
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 7.1.2
PRODUCT_PLATFORM_VERSION := 7.1.2
BOARD_RAMDISK_COMPRESS := gzip
#LZMA_RAMDISK := true
TW_EXCLUDE_APAT := true
TW_EXCLUDE_ENCRYPT := true
TW_EXCLUDE_SUPERSU := true
TW_IGNORE_MISC_WIPE_DATA := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_LIBRESETPROP := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_LPDUMP := true
TW_BASE_CONTROL_THEME := true
TW_EXCLUDE_ENCRYPTED_BACKUP := true
DISABLE_VUSE := true
TW_EXCLUDE_NTP := true
TW_NO_REBOOT_BOOTLOADER := true
TW_EXCLUDE_MTP := true
TW_NO_RADIO_COMM := true
BOARD_HAS_FLIPPED_SCREEN := false
#BOARD_HAS_NO_REAL_SDCARD := true
TW_USE_MODEL_HARDWARE := false
TW_SCREEN_BLANK_ON_BOOT := false
TW_NO_SCREEN_TIMEOUT := true
TW_DEBUG := true
TW_INCLUDE_LOGCAT := true
TW_INCLUDE_CRASH_HANDLER := true
TW_BRIGHTNESS_PATH := "/sys/class/backlight/backlight/brightness"
TW_MAX_BRIGHTNESS := 255
RECOVERY_GRAPHICS_USE_GLES := true
RECOVERY_GRAPHICS_USE_FBDEV := false
#TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
